baseURL = 'https://mimvoid.neocities.org/'
languageCode = 'en-us'
title = "mimvoid's little corner"
copyright = 'mimvoid © 2024'

uglyUrls = true
enableGitInfo = true
disableKinds = ['taxonomy', 'term']

[markup.highlight]
  style = 'dracula'
  tabWidth = 2

[menus]
  [[menus.tabs]]
    name = 'About'
    url = '/about'
    weight = 10
  [[menus.tabs]]
    name = 'Guestbook'
    url = '/guestbook'
    weight = 20
  [[menus.sidebar]]
    name = 'Biology'
    url = '/biology'
    weight = 10
  [[menus.sidebar]]
    name = 'Design'
    url = '/design'
    weight = 20
