basepageref = 'https://mimvoid.neocities.org/'
languageCode = 'en-us'

title = "mimvoid's little corner"
copyright = 'mimvoid © 2025'

uglyUrls = true  # allow .html extension
enableGitInfo = true  # let Git be used for the Lastmod param
disableKinds = ['taxonomy', 'term']  # I don't use these


[module]
[[module.mounts]]
source = 'content'
target = 'content'
excludeFiles = '**/*.zip'


[security]
enableInlineShortcodes = true

[frontmatter]
lastmod = ['lastmod', ':fileModTime', ':default']

[minify]
minifyOutput = true


[markup.highlight]
style = 'rose-pine-moon'
tabWidth = 2

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true
