basepageref = 'https://mimvoid.neocities.org/'
languageCode = 'en-us'
title = "mimvoid's little corner"
copyright = 'mimvoid © 2024'

uglyUrls = true
enableGitInfo = true
disableKinds = ['taxonomy', 'term']

[frontmatter]
  lastmod = ['lastmod', ':fileModTime', ':default']

[minify]
  minifyOutput = true

[markup.highlight]
  style = 'dracula'
  tabWidth = 2
[markup.goldmark.renderer]
  unsafe = true

[menus]
  [[menus.tabs]]
    name = 'About'
    pageref = '/about'
    weight = 10
  [[menus.tabs]]
    name = 'Guestbook'
    pageref = '/guestbook'
    weight = 20
  [[menus.sidebar]]
    name = 'Biology'
    pageref = '/biology'
    weight = 10
  [[menus.sidebar]]
    name = 'Design'
    pageref = '/design'
    weight = 20
