basepageref = 'https://mimvoid.neocities.org/'
languageCode = 'en-us'

title = "mimvoid's little corner"
copyright = 'mimvoid © 2024'

uglyUrls = true  # allow .html extension
enableGitInfo = true  # let Git be used for the Lastmod param
disableKinds = ['taxonomy', 'term']  # I don't use these


[frontmatter]
lastmod = ['lastmod', ':fileModTime', ':default']

[minify]
minifyOutput = true


[markup.highlight]
style = 'dracula'
tabWidth = 2

[markup.goldmark.parser.attribute]
block = true
